### ISSUE TITLE
WA cadastre data broken 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1139]
WA cadastre data is broken: https://nationalmap.gov.au/#share=s-uw7Q0kI0C0aWsmSGeSlaEbf0azk

To replace the service with the following working WMS servcies: 

- [ ] generic boundaries: https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Places_and_Addresses/MapServer/WMSServer 
- [ ] localities: https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Boundaries/MapServer/WMSServer 
- [ ] cadastre: https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Property_and_Planning/MapServer/WMSServer

Update 20 Jun 2022: 
- data services listed under Western Australia Government - Landgate subfolder are currently working 
- data service listed under National Datasets - Boundaries - Land Parcel and Property - By State - WA is currently broken
https://nationalmap.gov.au/#share=s-xgxrc2MDgT7XPChs9372nsr7dOF

![image](https://user-images.githubusercontent.com/18452161/174527705-1f90cd8d-541d-4a21-a1e2-0251074a3ecb.png)
- although a duplication, because cadastre is one of the most popular datasets, we need to copy the Cadastre Address web service (https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Places_and_Addresses/MapServer/WMSServer) to this curated catalogue sub-folder (to replace the broken one): https://nationalmap.gov.au/#share=s-clZ0tPqslpbP30jZWmdgcGdxkh4
- The small scale layer seems to perform better compared to the large scale 

![image](https://user-images.githubusercontent.com/18452161/174528110-2a78fb13-e065-481c-92e2-041622df5576.png)
-if we have issues adding just the one layer, we can add the group under a new "WA" subfolder in Land Parcel and Property - By State

**Comment by staffordsmith83** [comment]
@AnaBelgun WA Cadastre layers seem to be working? The provided sharelink shows no layers so Im not sure specifically which ones are broken. These work for me: https://nationalmap.gov.au/#share=s-oeeNETqVY2Z8ywNdUTvIoWJ2ZQY

**Comment by AnaBelgun** [comment]
yes, correct. the layers under WA State Gov do work, but the WA Cadastre layer under Boundaries is broken and we need to replace it with a working one (even if it's duplicate). The cadastre is very popular data hence why we want to make it easier for users to find it under the curated groups at the catalogue top.

**Comment by staffordsmith83** [comment]
@AnaBelgun , so just want to clear up:

there are two free cadastre layers in WA, there is [LGATE-001](https://catalogue.data.wa.gov.au/dataset/cadastre-no-attributes-lgate-001) which is in the landgate 'Property and Planning' group which aligns with the catalog group for this item. It is simplified boundaries with no attributes.

Then there is [LGATE-002](https://catalogue.data.wa.gov.au/dataset/cadastre-address-lgate-002) which is simplified boundaries with added address attribute, and which is in the landgate 'Places and Addresses' group.

The ticket specifies both of these... Which one do we want to use?

I think LGATE-002, even though it is not from `Property and Planning`, and we also show it in the Western Australia Government - Landgate subfolder. Because it has that added attribute and so is richer.
