### ISSUE TITLE
Investigate timeseries issue and legend png for Wave Atlas (WPS) 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1158]
User prompted that " the time series display is not working anymore (the one which was displayed at the bottom of the map)" 
![image](https://user-images.githubusercontent.com/18452161/175283989-a607afdd-1177-4101-b221-33fc024f34d3.png)

Wave atlas team is in parallel investigating if there are any issues with the service. 

PNG Issue:
Image not available any longer in workbench. 

![image](https://user-images.githubusercontent.com/18452161/181477765-c5283b55-a8e9-44e7-8a28-56df1d882671.png)

**Comment by nf-s** [comment]
### WPS: Tidal: Time-Series of 2D Tidal Data (Elevation / Velocity)

This process is returning Terria version 7 JSON data.

So the output will need to be converted to version 8 - or we can set `forceConvertResultsToV8: true` in our catalog

### WPS: Wave: Monthly Mean 

I tried to call the "Wave monthly mean" process with the following payloard

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
  <ows:Identifier>monthly-variations</ows:Identifier>
  <wps:DataInputs>
    <wps:Input>
      <ows:Identifier>LonLatPosition</ows:Identifier>
      <wps:Data>
        <wps:ComplexData>{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[114.84845949213732,-34.88680724263845,-1.2105764220972233]},"properties":{}}]}</wps:ComplexData>
      </wps:Data>
    </wps:Input>
    <wps:Input>
      <ows:Identifier>starttime</ows:Identifier>
      <wps:Data>
        <wps:ComplexData>{"type":"object","properties":{"timestamp":{"type":"string","format":"date-time","date-time":"2020-01-01T00:00"}}}</wps:ComplexData>
      </wps:Data>
    </wps:Input>
    <wps:Input>
      <ows:Identifier>stoptime</ows:Identifier>
      <wps:Data>
        <wps:ComplexData>{"type":"object","properties":{"timestamp":{"type":"string","format":"date-time","date-time":"2022-01-01T00:00"}}}</wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  <wps:ResponseForm>
    <wps:ResponseDocument storeExecuteResponse="true" status="true"/>
  </wps:ResponseForm>
</wps:Execute>
```

- and got this error from their server

```
Process error: method=Process.py._run_process, line=227, msg=&#39;Failed creating output for this request: cannot convert float NaN to integer&#39
```

### Image issue

Image data is unavailable due to blocked mixed content. 

The example I tried had URL http://oa-gis.csiro.au//wpsout2/46e2772f-36da-42f0/8559a3da-03a5-44a8/Annual_Waverose__Hs_vs_Dm__Climatology_at_lon_114.5031_lat_-34.3037_Year1.png

Which is not accessible on a HTTPS website. They will need to upgrade URLs to HTTPS

**Comment by nf-s** [comment]
Done
