### ISSUE TITLE
ABS Statistical boundaries - regrouping 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1169]
Reorganise ABS statistical boundaries by moving the layers under Year groups they belong (in case not already there)

![image](https://user-images.githubusercontent.com/18452161/184810998-7f46d8b4-eccc-4c47-b46c-ab2ab2890cad.png)

**Comment by mwu2018** [comment]
All datasets not in a year group should be for year `2011` according to their layer names. They are all hosted in nicta geoserver. Many of them have duplicates in group `2011` therefore should be removed. E.g. https://nationalmap.gov.au/#share=s-cZCm5ajE2lThqeelxOmiG6qQ09T.

**Comment by mwu2018** [comment]
The changes to be reviewed can be found at https://dev.vic.digitaltwin.terria.io/#share=s-lzpsOqef4XFmtNZPtNcdkJDjkfM, which can be compared to current catalog in the nationalmap at https://nationalmap.gov.au/#share=s-ytlLjYDbdJ9QcWFh3AK32nndTs0.
- Remove the parent group `Statistical boundaries` because all items are now in year groups.
- Several new year groups are created to accommodate items previously resided in year `2011`.
- All previously ungrouped items are either moved to year `2011` or deleted due to duplication.

**Comment by AnaBelgun** [comment]
tested randomly data in each group and they all seem to match the group year. so, all good to promote to test and prod. thank you @mwu2018
