### ISSUE TITLE
Clean up DEA duplicated services 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1172]
Catalogue entries to remove in bold below:

- [x] **Marine and Oceans / Coastal** and all it’s children – these seem to still work but are now widely out of sync with our naming conventions
- [x] **Vegetation / Fractional Cover** (folder and all children)
- [x] **Vegetation / Mangroves** (folder and all children)
- [x] **Water / Surface Water / GSKY** (folder and all children)
- [x] **Water / Water Observations from Space** (folder and all children)

All of these are broken and replaced with C3 equivalents under our folder structure so can be removed.

**Comment by AnaBelgun** [comment]
duplicate https://github.com/TerriaJS/nationalmap/issues/1200

**Comment by mwu2018** [comment]
@AnaBelgun 
What did you mean by "Marine and Oceans / Coastal and all it’s children – these seem to still work but are now widely out of sync with our naming conventions"?

Most of the group members work except for this one:
https://nationalmap.gov.au/#share=s-avTCEYNLkr1JohO8epqHaG7FdKe

**Comment by AnaBelgun** [comment]
@mwu2018 I'll double check with DEA team to see if the list is still accurate.

**Comment by CEKrause** [comment]
Yes, that list is still accurate. The most up-to-date versions of DEA data are in the "satellite imagery" folder. 

Is there a way to auto-pull from DEA's catalogue into the subcategories in National Map rather than maintaining them separately? All of the DEA datasets including our derived products are in "satellite imagery", which makes things like DEA Coastlines really hidden. 

Ideally we'd pull the "sea, ocean and coast" folder from "satellite imagery" into "Marine and Oceans / Coastal". At the moment it's maintained manually which is why the data in these folders (as listed in Ana's original issue at the top of this page) are all out of sync with our most recent datasets.

**Comment by mwu2018** [comment]
The DEA's "sea, ocean and coast" group is in this [file](https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/terria/dea-maps-v8.json). In order to use it in the nationalmap, it should be in its own json file.

**Comment by AnaBelgun** [comment]
@mwu2018 @CEKrause hi. We have discussed this previously and although we can harvest the entire Satellite imagery group from DEA to duplicate the Sea, Oceans and Coast under a different group in NationalMap, we need to set that up manually; still automatic harvesting of individual layers from DEA) but positioning in the catalogue is manual. 
If more visibility is needed for the Sea, ocean and coast data, we need to copy that entire folder under Marine & Oceans group. 
Are you ok with that @CEKrause ?

**Comment by CEKrause** [comment]
For now, can you just remove the list of datasets in the original ticket, and we will work out how to better present our data in National Map as a separate issue.
Is that ok with you @AnaBelgun?

**Comment by AnaBelgun** [comment]
hi @CEKrause yes, ok. thank you for letting us know. We will then leave the Marine and Oceans group as is (i.e. without manually duplicating the Sea, oceans and coast group. @mwu2018 I think we are done here and can close.
