### ISSUE TITLE
Queensland state data broken

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1176]
Most of the QLD state data groups are broken

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/6187649/190407776-373227c7-5f97-431a-aba4-de855e065b2f.png">

**Comment by meh9** [comment]
They are decommissioning this service in favour of https://spatial-gis.information.qld.gov.au/arcgis/rest/services

The message on e.g. the Farming folder is:

<img width="1312" alt="Screen Shot 2022-09-20 at 15 27 31" src="https://user-images.githubusercontent.com/5283003/191174588-b4d06899-3266-4e42-8748-891dbbbd7975.png">

Instead of doing all the subservices individually, why don't we just specify the root of https://spatial-gis.information.qld.gov.au/arcgis/rest/services and render the hierarchy automatically?

**Comment by AnaBelgun** [comment]
To filter out: 
- QLD globe sub category because it's based on user authentication

**Comment by AnaBelgun** [comment]
Fixed. All services updated.
