### ISSUE TITLE
Queensland local gov data broken

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/nationalmap#1177]
Most of the QLD Local gov groups are broken

<img width="520" alt="image" src="https://user-images.githubusercontent.com/6187649/190407912-29299da2-d27b-4fbf-a4a9-aea9ccf9d1be.png">

**Comment by meh9** [comment]
From what I can tell the "broken" ones are not actually broken, there just isn't any data. E.g. `Fraser Coast` does a search on DGA:

https://data.gov.au/search?organisation=Fraser%20Coast%20Regional%20Council

But there is only one dataset and it doesn't have a geospatial view, so there isn't anything to show.

(Note that e.g. `Brisbane City Council` works differently and connects directly to the https://www.data.brisbane.qld.gov.au/data CKAN server and that's why it works.)

How did we get this list of LGA's in the first place? Why do we have `Fraser Coast` at all?

We should just remove `Fraser Coast` and any other that come from DGA that have no layers.

**Comment by AnaBelgun** [comment]
to be fixed together with all LGAs
