### ISSUE TITLE
Remove YDYR - Analysis tools 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1203]
Remove from YDYR from Analysis tools 
Add satellite imagery use case of delta/difference tool

**Comment by steve9164** [comment]
Since the satellite imagery layers that support difference/delta already exist in the catalogue, and it's undefined behaviour to have 1 item twice in the catalogue, I think it'd be best to include layers by making a copy of them. This should be possible by using the terria catalogue reference with a path to the layer, but give it a different id (probably best to give it a 8-10 character random id). Ensure that the id you choose is used for both the reference and the target model when loaded rather than the id defined by DEA.

**Comment by mwu2018** [comment]
Please clarify if my understanding is correct.
There are a few (3, I think) satellite imagery items such as [DEA Surface Reflectance (Landsat and Sentinel-2)](https://nationalmap.gov.au/#share=s-aNHUyje8nAbthAWyPGDq2XIaw05) that can use difference tool to performance analysis. We need to make copies of those items in the group of `Analysis Tools` so that a user can performance analysis like [this](
https://nationalmap.gov.au/#share=s-brE2NZrXjoJm6uKL6pWqyyfFFD0).

**Comment by AnaBelgun** [comment]
@mwu2018 hi, yes, that's the dataset 
I will write the step by step guide and put the content here

**Comment by steve9164** [comment]
@mwu2018 Perfect! Thanks.

**Comment by AnaBelgun** [comment]
@mwu2018 you can try to include this guide and video: https://userguide.terria.io/interactions-functionalities-and-workflows#change-detection-delta-workflow

**Comment by mwu2018** [comment]
@AnaBelgun If you are ok with [this](https://nationalmap.dev.saas.terria.io/#share=s-hmRXaFLt8zdw0tQcXFNjKCfxPMJ), I will copy it to `test` and `prod`.

**Comment by AnaBelgun** [comment]
hi @mwu2018 thank you. I've made some changes below:

**Name of dataset in the catalogue** - Change detection using DEA Surface Reflectance (Landsat and Sentinel-2)
**Description** - This catalogue group will include examples of tools and workflows aimed at specific use cases. 
The first example is the "Change detection" workflow aimed at understanding variances in vegetation cover when using satellite imagery such as Landsat and Sentinel-2. Check this [guide](https://userguide.terria.io/interactions-functionalities-and-workflows#change-detection-delta-workflow) for more information.

**Comment by mwu2018** [comment]
@AnaBelgun Done.

**Comment by AnaBelgun** [comment]
please do @mwu2018
