### ISSUE TITLE
Check 'search' not showing existing datasets in list of results

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#1217]
Investigation on why some datasets do not show up in search results. 
Check Cadastre Address (LGATE-002). 
When adding that dataset from Western Australia - State government - Landgate subgroup it performs as expected.

**Comment by staffordsmith83** [comment]
UPDATE 2 August 2023:

Nick used to update the index to fix this issue?

**Comment by na9da** [comment]
@AnaBelgun - the specific example of LGATE datasets you gave failed due to a transient error (timeout during crawling). It fixed itself when I re-ran the indexer just now.

A longer term solution would be to look at merging the indexes from past 3 days to smooth over transient errors so that an item that failed due to timeout stays in the index for 3 consecutive days before it gets removed. I could have a look at implementing that.

**Comment by na9da** [comment]
Have created a new ticket for investigating on making the index [resistant to transient errors](https://github.com/TerriaJS/saas-catalogs-public/issues/345).
