### ISSUE TITLE
Some share links not working

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/nationalmap#398]
Looking at https://www.communications.gov.au/what-we-do/phone/mobile-services-and-coverage/mobile-black-spot-program - the NationalMap share link doesn't work properly - giving "Error loading initialization source"

(http://nationalmap.gov.au/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22sharedCatalogMembers%22%3A%7B%22Root%20Group%2FNational%20Data%20Sets%2FCommunications%2FMobile%20Black%20Spot%20Database%22%3A%7B%22nowViewingCatalogItem%22%3A%7B%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A1%2C%22keepOnTop%22%3Afalse%2C%22type%22%3A%22wms%22%2C%22id%22%3A%22Mobile%20Black%20Spot%20Database%22%2C%22parents%22%3A%5B%5D%7D%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22type%22%3A%22ckan-resource%22%2C%22id%22%3A%22Root%20Group%2FNational%20Data%20Sets%2FCommunications%2FMobile%20Black%20Spot%20Database%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FNational%20Data%20Sets%22%2C%22Root%20Group%2FNational%20Data%20Sets%2FCommunications%22%5D%7D%7D%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A95.2043925952281%2C%22south%22%3A-37.62879848527344%2C%22east%22%3A171.79560744413303%2C%22north%22%3A-7.245830946200606%2C%22position%22%3A%7B%22x%22%3A-7963013.714426368%2C%22y%22%3A8391265.58960224%2C%22z%22%3A-5754448.042772252%7D%2C%22direction%22%3A%7B%22x%22%3A0.6154884686037506%2C%22y%22%3A-0.648589515554248%2C%22z%22%3A0.447778500297765%7D%2C%22up%22%3A%7B%22x%22%3A-0.3082303795772533%2C%22y%22%3A0.32480704800631693%2C%22z%22%3A0.8941445155404603%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Bing%20Maps%20Aerial%20with%20Labels%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D&activeTabId=DataCatalogue/)

Is this something to do with something we've changed?

**Comment by kring** [comment]
Sort of.  This is similar to the problem I described in https://github.com/TerriaJS/terriajs/issues/2302.  In this case, though, the share link includes `init/nm.json` which is the old catalog file (from before we started hosting catalogs on S3 so that we can update them).  That file doesn't exist anymore, so we get an error.

The good news is that it still "works" other than the error message.  And the other good news is that fixing https://github.com/TerriaJS/terriajs/issues/2302 should fix this too.  The bad news is I'm still not entirely sure of the best way to fix it.
