### ISSUE TITLE
Single inverted comma appearing as incorrect symbol

### ISSUE THREAD

**Issue by MakeupArtist** [TerriaJS/nationalmap#436]
![screenshot from 2017-02-21 11 10 49](https://cloud.githubusercontent.com/assets/25913085/23145936/77a0a144-f826-11e6-96e2-ec0024842319.png)

The word " don't " in the first line of text in the story article is showing an incorrect symbol where the single inverted comma should appear.

**Comment by kring** [comment]
Any better front end devs than me (@chloeleichen @AlexGilleran @RacingTadpole) know how we might fix this?  Safe to say the content was written in something like MS Word and includes an unusual non-ascii character instead of the normal apostrophe.  Is this a font limitation (like maybe we need to include a wider range of characters in our Google Font loading)?  Or a character encoding problem maybe?
