### ISSUE TITLE
Data preview doesn't zoom for non-Australian added data

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/nationalmap#437]
When adding a data source to NationalMap (such as http://cga-app01.cadm.harvard.edu/arcgis/rest/services/darmc/roman/MapServer) 

the data preview stays focussed on Australia
![image](https://cloud.githubusercontent.com/assets/4373945/23192221/66f12668-f8f6-11e6-8cb5-045d8bd26cd9.png)
until you click in it
![image](https://cloud.githubusercontent.com/assets/4373945/23192246/84708332-f8f6-11e6-8236-1df8de80f7ae.png)

**Comment by kring** [comment]
This is "by design" but also kind of silly.  The default preview is supposed to show where the dataset is located rather than zooming in close to it (which lets you see it, maybe, but doesn't show you where it is).  When you click, it zooms in.

But we basically assume that all datasets are in Australia (or within your map's default view, whatever it is).

We should detect when a dataset's bounding box is not contained by the map's default view, and show the whole world for context instead of showing the default view.

**Comment by tobybellwood** [comment]
agree with the logic - should have used pan, not zoom in my issue!!

**Comment by AnaBelgun** [comment]
new issue: https://github.com/TerriaJS/terriajs/issues/3007
