### ISSUE TITLE
Pre prod test v2017-03-15 - Error loading GA catalog items

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#462]
Catalog items under 'Data Providers/Geoscience Australia' generating following error:
'Error loading KML or KMZ'

Layers tested generating errors include:

- Adelaide Special 1:250 000 GIS Dataset
- Abminga 1:250 000 GIS Dataset
- Penola Special 1:250 000 GIS Dataset
- Perth Special  1:250 000 GIS Dataset

**Comment by tobybellwood** [comment]
This is the well-known kml dressed as a zip file problem.

**Comment by steve9164** [comment]
```
XMLHttpRequest cannot load https://d28rz98at9flks.cloudfront.net/64237/64237_si54-09_kml.zip. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://preprod.nationalmap.gov.au' is therefore not allowed access.
```

Looks like a CORS issue first and foremost (It's possible that even after fixing that there will still be issues with being ".zip")

There are a few ways to fix the CORS issue:
- Enable CORS on the server (probably the best option)
- Alias the server under some .gov.au domain (since NationalMap automatically trusts and proxies servers in .gov.au domain)

**Comment by kring** [comment]
Closing this because it does not appear to be a problem with NationalMap itself.
