### ISSUE TITLE
GA Prehost test v2017-04-13 - Error loading KML or KMZ

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#479]
Error displayed when attempted to open:

Data Providers/Integrated Marine Observation System (IMOS)/ IMOS AUV Campaign ... 16 Nov 2010

**Comment by steve9164** [comment]
Another CORS error. Could be fixed by adding data.aodn.org.au to our allowed domains for proxying.

**Comment by kring** [comment]
Added `data.aodn.org.au` to the proxy whitelist, but that dataset still doesn't work because the KML file is missing.  i.e. http://data.aodn.org.au/IMOS/public/AUV/Batemans201011/r20101117_001912_batemans_03_site1sz/track_files/batemans_03_site1sz.kml

Not a NationalMap problem, so I'm closing this.
