### ISSUE TITLE
Error loading namespaced WMS layer

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#541]
- Catalogue group: Data.gov.au/CMAR - CSIRO Marine and Atmospheric Research
- Layers generating 'Error loading KML or KMZ error (see slide below)

![slide4](https://user-images.githubusercontent.com/22827786/28651234-ec839648-72c3-11e7-9c32-82b910f6d14e.JPG)

**Comment by ajbar7** [comment]
I couldn't get the KML / KMZ issue but this is harvest thing with the Australian Oceans Data Network CSW Harvester. I think this maybe because a layer (WMS Layer ID) is not declared at http://data.gov.au/dataset/australian-ship-reporting-system-and-automatic-identification-system-shipping-summari-1999-2015/resource/7fdcd6c7-adb3-46c5-8d9c-32a3516d5277. 

@kring / @steve9164 would be worth putting in something that makes it ignore layers where it doesn't know the layer id or would that be counter productive?

**Comment by kring** [comment]
In this case, the WMS URL is a `GetMap` request, and it includes a `layers` parameter, so we _do_ know the layer and use it.  If we can't deduce a layer at all, it will be excluded.

The problem, though, is that the layer name specified in the GetMap request (`nerp:ausrep_shipping_1999`) is not actually present in the `GetCapabilities`.  Only the unqualified name (`ausrep_shipping_1999`) is present.  We can't determine this before showing it in the catalog because that requires us to download the GetCapabilities document.  It would take much too long to do that for every WMS server in the group.

**Comment by ajbar7** [comment]
What's the sensible option then? Is it something that's a problem with the configuration of that Geoserver that needs to be brought up with the service owner? Or is it layer specific?

**Comment by kring** [comment]
I think a reasonable solution is to change the URL to include the non-namespaced layer name.  IMO it's a questionable design choice of Geoserver that namespaced layers don't show in GetCapabilities, but as far as I know there's no configuration option to change that.  We could also teach TerriaJS about the Geoserver namespace extension to WMS, which is described here:
http://docs.geoserver.org/stable/en/user/services/wms/vendor.html#namespace

Off the top of my head, I think what that would mean is that we first try a regular GetCapabilities, and if we fail to find the layer there, we assume the part before the `:` is a namespace, request the GetCapabilities for that namespace, and see if we can find it there.  Or maybe we always try the namespaced version first...

**Comment by ajbar7** [comment]
Well - given that we don't run the catalogue at the other end what would make it work with more sources? I think that would be the better option to pursue.

**Comment by kring** [comment]
I wrote an issue for this, TerriaJS/terriajs#2630.
