### ISSUE TITLE
National Map v2017-08-15 pre-release test - Observation - Layer zoom to extent setting

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#566]
**Observation**

Layer: Data.gov.au/Antarctic Climate and Ecosystems Cooperative Research Centre/Climate Futures Tasmania - Scenario's A2 and B1

Incorrect setting for layer 'Zoom to Extent' function

- Current setting centres map in the middle of Indian Ocean
- Need to set to extents of data displayed over Tasmania

See images below.

![slide8](https://user-images.githubusercontent.com/22827786/29501288-df9ec00a-866a-11e7-9698-0ee5b939f70d.JPG)

![slide9](https://user-images.githubusercontent.com/22827786/29501291-e6b7b680-866a-11e7-9723-2fab911eb8e6.JPG)

![slide10](https://user-images.githubusercontent.com/22827786/29501297-ee9a1fb4-866a-11e7-8951-7f502be1e470.JPG)

**Comment by kring** [comment]
@EhsanCanberra it's not helpful to identify problems with the metadata on data.gov.au as part of NationalMap testing - it's just not something we can fix.  If you know of a dataset on data.gov.au where the metadata is correct and yet it is being incorrectly interpreted by NationalMap, by all means write an issue here!

But otherwise, perhaps make a note on the dataset's page on data.gov.au by leaving a comment, because only the data custodian will be able to fix the problem, not us.

**Comment by EhsanCanberra** [comment]
@kring Understood. However, issues are registered as they are detected by the GA pre-release test. It is up to Data61 to determine how to respond and resolve them. Thank you for your comment - I have edited the issue to reflect it as an 'Observation' :)

**Comment by kring** [comment]
The ArcGIS is reporting an incorrect "full extent".  Not something we can fix in NationalMap.
