### ISSUE TITLE
Change elevation to use AHD

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/nationalmap#59]
We've had requests to change the elevation data to show Australian Height Datum for NM (Terria should be configurable so that this is an option for developers and NM would use AHD).  DoC and GA would prefer that NM uses AHD too.

**Comment by kring** [comment]
The grid file necessary to interpolate AHD / AUSGeoid09 heights is over 100 megabytes (about half that gzipped), so that's not really practical to download to the client.  So we have two options:
1) Store the data file only on the server, and write a service to query AHD heights.  We'd just include AHD in the error bounds when the mouse is moving and do the service request only when the mouse stops (much like the way we query terrain already).
2) Use the EGM96 model instead, which has only a 2 megabyte grid file, and do the interpolation on the client.  EGM96 is within half a meter of AHD.  Considering that our terrain data is not accurate to anywhere near half a meter anyway, the results won't really be appreciably worse, but we won't be able to say "we do AHD" with this approach.

**Comment by kgrochow** [comment]
Sounds like a great thing for GA to possibly work on given their current terrain server work.

**Comment by bsimyo** [comment]
I've checked with DoC and GA.  They are happy to go with EGM96 for now and put AHD into the roadmap for later (for either GA or NICTA to do TBD).

**Comment by kring** [comment]
The elevation display is now relative to EGM96.  I'm leaving this issue open to remind us to switch to AHD at some point.
