### ISSUE TITLE
National Map v2017-10-16 pre-release - Observation Tasmania Map 250k Resolution

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/nationalmap#605]
Layer: Unable to load data layer first

 - After acknowledging the error then it will happily load on future clicks in the same browser session. If you start a new session the about repeats.
![slide6](https://user-images.githubusercontent.com/20634718/31693638-7e2573ba-b3eb-11e7-97cf-7d16a4a890a4.JPG)

**Comment by kring** [comment]
This is caused by a slightly dodgy value for the `Abstract` field for this layer on the TAS WMS server.  The value is:

```
TASMAP 1:250 000 Images have been generated from the latest Edition 5 2014 edition of the TASMAP 1:250 000 map series which have been georeferenced and mosaiced into a state-wide dataset. For Services Terms and Conditions, please see the
<a href="" target="">LIST Web Services Terms and Conditions</a>
(http://listdata.thelist.tas.gov.au/public/LISTWebServicesTermsConditions.pdf)
```

Note that the abstract includes some HTML.  This is fine, but it should be inside a `CDATA` block so that the HTML isn't interpreted as part of the XML structure.  This is what is happening here: NationalMap considers that `<a>` to be a sub-element of the `Abstract`, and so the Abstract is not a simple string, and so we get this error when the non-string is fed through to somewhere that expects a string.

I'd argue that the server is returning bad data (this is not actually a valid GetCapabilities XML document), but we can be more tolerant of it in TerriaJS.

**Comment by kring** [comment]
I wrote TerriaJS/terriajs#2721 to capture this.
