### ISSUE TITLE
National Map v2018-01-18 pre-release test - All links for CMAR - CSIRO Marine and atmospheric Research Return 500 error code

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#669]
All links under data.gov.au -> CMAR - CSIRO Marine and atmospheric Research returns an status code 500 error on the national maps app. 

However the links for the Data Url (http://www.data.gov.au/dataset/australian-ship-reporting-system-and-automatic-identification-system-shipping-summari-1999-2015) and Web Map Service (WMS) URL (https://www.cmar.csiro.au/geoserver/nerp/wms) returns data indicating that the server is available. 

Screenshot below
![image005](https://user-images.githubusercontent.com/35437484/35131941-b8534e22-fcc0-11e7-8815-f6adb0e1c45a.jpg)

**Comment by kring** [comment]
The problem here is that the server (www.cmar.csiro.au) is providing an incomplete TLS certificate chain, and terriajs-server currently cannot handle that. Technically this is a misconfiguration of the server, but most clients can deal with it.

We have similar problems with communications.gov.au, but it's less of an issue there because requests to that server usually do not go through the proxy.

**Comment by kring** [comment]
I've written TerriaJS/terriajs-server#78 to cover this issue.
