### ISSUE TITLE
National Map v2018-01-18 pre-release test - Bioregional Conservation Status -Endangered returns error

### ISSUE THREAD

**Issue by jimmyjamesga** [TerriaJS/nationalmap#674]
The Bioregional Conservation Status -Endangered returns error

The wms link returns an xml with a null pointer exception in the xml page

Screenshot below
![image014](https://user-images.githubusercontent.com/35437484/35132973-c48977ac-fcc5-11e7-997f-604974d310a5.jpg)

**Comment by AnaBelgun** [comment]
this is probably because of changes to the service made by the VIC Dept. of Environment. 
@kring please confirm, and I'll notify them and fix in the next release.

**Comment by kring** [comment]
I can't quite see in the screenshot where the layer is located in the catalog, nor what the error was.  I tried Victorian Government -> Biology & Ecology -> Bioregional Conservation Status -Endangered, and I get:
![image](https://user-images.githubusercontent.com/924374/35207515-8e769616-ff97-11e7-8d23-a3934bc71dc9.png)

Assuming this is the right layer, the problem is that the Vic CKAN server has a layer name that doesn't exist.  You can confirm this by going to https://www.data.vic.gov.au/data/dataset/bioregional-conservation-status-endangered and clicking the WMS URL after checking the box to agree to the terms.  Your browser will download an XML with a "could not find layer" error.

So not something we can fix in NationalMap.
