### ISSUE TITLE
National Map v2018-05-22 pre-release test - Data load error - School of Animal Biology - Clams

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/nationalmap#757]
Error loading data
Layer: Data.gov.au/School of Animal Biology (SAB), The University of Western Australia (UWA)/WAMSI Node 3.2.2b - Diversity, abundance and distribution of intertidal invertebrate species in the Ningaloo Marine Park - Small giant clams (Tridacna maxima)

![slide2](https://user-images.githubusercontent.com/22827786/40466197-c948b99c-5f67-11e8-891b-ef7b5f7c788d.JPG)

**Comment by AnaBelgun** [comment]
Error loading KMZ
Tried to download the csv (under the same resource on data.gov.au) and data doesn't exist (even in csv)

**Comment by AnaBelgun** [comment]
Emailed data.gov.au to check the resource.

**Comment by QuadTog** [comment]
Hey Ana,

Took a quick look and yeah the resource(s) aren't there. We're the landing page for this data but it's actually stored with AODN: http://catalogue.aodn.org.au/geonetwork/srv/eng/metadata.show?id=2310&currTab=advanced

Example:
WAMSI3.2.2bGiantClams.csv
Resource last updated 31/5/2011.
http://146.118.96.76:8080/geonetwork/srv/en/resources.get?uuid=18e12554-c65f-492d-b125-8b8974352d66&fname=WAMSI3.2.2bGiantClams.csv&access=private

I believe that data isn't pulling through because access is private until you fill out a Creative Commons 2.5 License Agreement.

Kind Regards,
Adam Rice

**Comment by AnaBelgun** [comment]
thanks @QuadTog followed up with them too :+1:

**Comment by QuadTog** [comment]
Data is at:
https://data.pawsey.org.au/public/?path=/WA%20Node%20Ocean%20Data%20Network/WAMSI1/Node3/3.2/3.2.2b

and I'm able to download WAMSI3.2.2bGiantClams.csv with no issues from:
https://data.pawsey.org.au/download/WA%20Node%20Ocean%20Data%20Network/WAMSI1/Node3/3.2/3.2.2b/WAMSI3.2.2bDataAndMetadata/WAMSI3.2.2bGiantClams.csv

Data Provider advised they're going to be migrating their data to Data.wa which'll fix the broken URLs.

**Comment by AnaBelgun** [comment]
Thanks @QuadTog
