### ISSUE TITLE
Add WA Dept of Planning WMS 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#866]
Some WA Dept of Planning layers part of this WMS Server https://services.slip.wa.gov.au/public/services/SLIP_Public_Services/Property_and_Planning/MapServer/WMSServer are not available in the NationalMap catalogue. 

All need to be accessible. 

(test: e.g. Bush Forever Areas)

**Comment by rowanwins** [comment]
So currently the WA data comes via [their CKAN instance](https://data.wa.gov.au/) however [we're only grabbing things](https://github.com/TerriaJS/NationalMap-Catalog/blob/master/datasources/includes/WA.ejs#L6) that are available as WMS.

So basically anything that can be seen on this page is being picked up
https://catalogue.data.wa.gov.au/dataset?organization=department-of-planning&res_format=WMS

We're picking up [Bush Forever Areas](https://catalogue.data.wa.gov.au/dataset/bush-forever-areas-2000-dop-071) however there are other layers we're missing because they haven't been published to their data.wa.gov 
![BushForver](https://user-images.githubusercontent.com/6735870/60690279-941d9700-9f09-11e9-8fc7-23f54c587ade.png) 

I'm not sure if there is a good way to manually add that single WMS endpoint into the catalog but I can take a look. The other workaround is for the WA people to publish the other layers to CKAN.

**Comment by AnaBelgun** [comment]
to note that some layers are duplicates with one layer asking for user login when selected.

**Comment by AnaBelgun** [comment]
possibly related to this: https://github.com/TerriaJS/nationalmap/issues/848

**Comment by AnaBelgun** [comment]
Notified WA Dept of Planning and suggested they include all layers in the data.wa.gov.au CKAN instance. Nothing to do at this stage at our end. Will close it and reopen once the Dept replies replies with more details.
