### ISSUE TITLE
Reorganise water data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#915]
Based on discussions with main data custodians (BoM and GA) and the FSDF themes, water data needs more clarity: 

- [x] create a Water catalogue group in the main catalogue

- [x] create a Marine & Oceans group as well and move all the marine related data: the layer from Australian Institute of Marine Science (delete the subgroup); Bathymetry; Coastal; from Individual hydrology and marine layers subgroup include: marine swamps, saline coastal flats, 

- [x] create 3 subgroups under Water: Ground water; Surface Water; Water Observations from Space

- [x] under Surface Water, add a sub-group: Water stations data and within the sub-group, add the 2 Water regulations data layers from NEII Viewer: http://neii.gov.au/viewer/#share=s-8dywbyuD72Ik3FQ27uo6dX1VXc0

**Comment by reginapramesti** [comment]
@AnaBelgun for the 2 water regulations data layers, should I name the group as `Water Stations Data` or `Water Regulations Data (BoM)` just like in NEII Viewer?

(For now I will be naming the group as `Water Stations Data`)

**Comment by AnaBelgun** [comment]
@reginapramesti water stations seems clearer than water regulations

**Comment by RussellGrew** [comment]
Hi @AnaBelgun 

It was good to meet at D61+ Live.

I wonder if this is related to TerriaJS/terriajs#3705 ?

I am pretty good at crashing NEII with these data. Often when I click the green expand button to see the chart the map crashes and the whole screen goes white. Firefox 69.0.1 here. Also IE. It seems more of an issue for watercourse levels rather than discharge. Example here http://www.neii.gov.au/viewer/#share=s-y0Vif1nUZdLmhmba0Gglv0NRcpY

I hope this helps.

**Comment by AnaBelgun** [comment]
Hi @RussellGrew thanks for the feedback. 
The SOS issue is not related to the catalogue reorganisation. In this ticket, we're trying to make the water data catalogue more consistent and clearer for users. 
We're in the process of working with the Bureau on the performance issue with the Water Regulations (discharge and levels) services.
