### ISSUE TITLE
NBN data legend visualisation on NatMap - to investigate 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/nationalmap#966]
ACMA has published a nr of new datasets on data.gov.au which are now in the National Map catalogue and they want the legend to appear pink. 

- Go to Data.gov.au group - Statutory Infrastructure Provided - NBN and Statutory Infrastructure Provider - Opticomm
- When adding the Opticomm layer as wms (not the GeoJSON), the legend appears green https://nationalmap.gov.au/#share=s-qkZOvHxoJ75j9DfihJceLa4qGYV - testing this service https://data.gov.au/geoserver/statutoryinfrastructureprovideropticomm/wms (from data.gov.au via their geoserver: http://www.data.gov.au/dataset/statutoryinfrastructureprovideropticomm) 

![image](https://user-images.githubusercontent.com/18452161/88362348-8d391f00-cdbf-11ea-84e8-22031ae64d0d.png)

- testing same service https://data.gov.au/geoserver/statutoryinfrastructureprovideropticomm/wms on https://terria-cube.terria.io/ or other maps, legend appears pink, https://terria-cube.terria.io/#share=s-mUYwD04KLhxAHDxmv7F5EHjPWyn

![image](https://user-images.githubusercontent.com/18452161/88362404-b6f24600-cdbf-11ea-846e-8cb29e5e16fa.png)

Investigation done by data.gov.au determined it's a cache problem on NationalMap and wondered is we could flush the cache on National Map eg. This legend graphic is still green https://nationalmap.gov.au/proxy/http://data.gov.au/geoserver/statutoryinfrastructureprovideropticomm/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=ckan_8600f5d8_e639_4d01_bcfd_ba6e9a47d06a&version=1.1.0&transparent=True&LEGEND_OPTIONS=fontSize%3A14%3BforceLabels%3Aon%3BfontAntiAliasing%3Atrue&srs=EPSG%3A3857 but accessed directly it is not https://data.gov.au/geoserver/statutoryinfrastructureprovideropticomm/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=ckan_8600f5d8_e639_4d01_bcfd_ba6e9a47d06a&version=1.1.0&transparent=True&LEGEND_OPTIONS=fontSize%3A14%3BforceLabels%3Aon%3BfontAntiAliasing%3Atrue&srs=EPSG%3A3857

**Comment by AnaBelgun** [comment]
More details from ACMA: 
That is correct,
-	I originally uploaded an incorrect .sld file with incorrect legend colour and label, to data.gov. 
-	I removed that .sld and replaced it with the correct one (pink legend and label “OptiComm” not “nbn co”
-	When I view the data on the NatMap, if I zoom in far enough it actually will show the area as green initially, but if I keep zooming it gradually turns the area pink.

In addition to this, we have had reports from NBN Co that their dataset: https://data.gov.au/data/dataset/ed264f72-5fdf-4a54-8381-d35a10c7c85a 
when viewed on the NatMap: https://data.gov.au/data/dataset/statutoryinfrastructureprovidernbncolimited/resource_edit/e0a74acf-92a0-4ae0-a5eb-16c26bc33c79 
Seems to have a similar issue as it only seems to load their most recent and complete data file when zoomed in far enough. (Areas which “Fixed-wireless” can only be located when zoomed right in. The resource: https://data.gov.au/dataset/ed264f72-5fdf-4a54-8381-d35a10c7c85a/resource/2bd3f546-8ade-4d8e-99da-42e38196dca6/download/nbn_co_limited.zip was replaced to include the “Fixed-Wireless” areas)

**Comment by soyarsauce** [comment]
There are 4 levels of caches at play here, for a request from that geoserver that gets passed through the terriajs proxy:
- geoserver cache
- varnish (at NationalMap level) cache - this is the likely culprit
- cloudfront cache
- browser cache

terriajs-server & its proxy doesn't actually serve as a cache. The proxy itself however, sends a 2 week cache header by default when a dataset doesn't specify a cache duration, and this can get picked up by anything between geoserver and the browser. The likely thing that's happened here is the green version of the .sld got picked up by varnish and is sitting there until it expires, 

My suspicion is on varnish because that's the difference with nationalmap and terriacube, the terria cube share link above also goes through the terria-cube proxy, and observing the behaviour of requests fed through those respective proxies.

Restarting the NM server, or even simply re-deploying nationalmap will clear the varnish cache & should solve this immediate problem.

Given the discussions surrounding the time sensitivity, If these datasets are going to be updated at a frequency that's under this default 2 week duration, we should pull them out of the DGA & configure a shorter cache duration for these items in the short term. Alternatively, addressing https://github.com/TerriaJS/nationalmap/issues/967 & allowing data.gov.au to be accessed directly instead of through the proxy will also allow "automatic harvesting" of the latest information without extra configuration on the catalog end.
cc @AnaBelgun

**Comment by AnaBelgun** [comment]
Understood that if this https://github.com/TerriaJS/nationalmap/issues/967 is fixed, the legends will be updated

**Comment by AnaBelgun** [comment]
fixed in new NatMap release
 https://preprod.nationalmap.gov.au/
